version: "3.8"
services:
  web:
    build: .
    restart: always
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    env_file:
      - .env
